services:
  re-challenge:
    build: .
    container_name: re-challenge
    depends_on:
      re-challenge-postgres:
        condition: service_healthy
    environment:
      - POSTGRES_DB=re-challenge
      - POSTGRES_PASSWORD=re-challenge-password
      - POSTGRES_PORT=3002
      - POSTGRES_URL=host.docker.internal
      - POSTGRES_USER=re-challenge-user
    ports:
    - 3001:3001
  re-challenge-postgres:
    container_name: re-challenge-postgres
    env_file:
      - ./docker/env/Postgres.env
    image: 'postgres:16.4'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U re-challenge-user -d re-challenge"]
        interval: 5s
        timeout: 3s
        retries: 5
    ports:
      - 3002:5432
    restart: on-failure
    volumes:
      - re-challenge-volume:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
volumes:
  re-challenge-volume:
    external: false